// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	velero "github.com/vmware-tanzu/velero/pkg/plugin/velero"
)

// SearchProvider is an autogenerated mock type for the SearchProvider type
type SearchProvider struct {
	mock.Mock
}

// NewSearchProvider creates a new instance of SearchProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewSearchProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SearchProvider {
	m := &SearchProvider{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// DeleteBackup provides a mock function with given fields: ctx, backupName
func (_m *SearchProvider) DeleteBackup(ctx context.Context, backupName string) error {
	ret := _m.Called(ctx, backupName)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, backupName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// IndexBackup provides a mock function with given fields: ctx, backupName, tarballURL
func (_m *SearchProvider) IndexBackup(ctx context.Context, backupName string, tarballURL string) error {
	ret := _m.Called(ctx, backupName, tarballURL)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, backupName, tarballURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Init provides a mock function with given fields: config
func (_m *SearchProvider) Init(config map[string]string) error {
	ret := _m.Called(config)

	var r0 error
	if rf, ok := ret.Get(0).(func(map[string]string) error); ok {
		r0 = rf(config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ListIndexedBackups provides a mock function with given fields: ctx
func (_m *SearchProvider) ListIndexedBackups(ctx context.Context) ([]string, error) {
	ret := _m.Called(ctx)

	var r0 []string
	if rf, ok := ret.Get(0).(func(context.Context) []string); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MarkReady provides a mock function with given fields: ctx
func (_m *SearchProvider) MarkReady(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Ready provides a mock function with given fields: ctx
func (_m *SearchProvider) Ready(ctx context.Context) (bool, error) {
	ret := _m.Called(ctx)

	var r0 bool
	if rf, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Search provides a mock function with given fields: ctx, params
func (_m *SearchProvider) Search(ctx context.Context, params velero.SearchParams) (velero.SearchResult, error) {
	ret := _m.Called(ctx, params)

	var r0 velero.SearchResult
	if rf, ok := ret.Get(0).(func(context.Context, velero.SearchParams) velero.SearchResult); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Get(0).(velero.SearchResult)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, velero.SearchParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
