// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	process "github.com/vmware-tanzu/velero/pkg/plugin/clientmgmt/process"
)

// RestartableProcess is an autogenerated mock type for the RestartableProcess type
type RestartableProcess struct {
	mock.Mock
}

// AddReinitializer provides a mock function with given fields: key, r
func (_m *RestartableProcess) AddReinitializer(key process.KindAndName, r process.Reinitializer) {
	_m.Called(key, r)
}

// GetByKindAndName provides a mock function with given fields: key
func (_m *RestartableProcess) GetByKindAndName(key process.KindAndName) (interface{}, error) {
	ret := _m.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetByKindAndName")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(process.KindAndName) (interface{}, error)); ok {
		return rf(key)
	}
	if rf, ok := ret.Get(0).(func(process.KindAndName) interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(process.KindAndName) error); ok {
		r1 = rf(key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Reset provides a mock function with no fields
func (_m *RestartableProcess) Reset() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResetIfNeeded provides a mock function with no fields
func (_m *RestartableProcess) ResetIfNeeded() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ResetIfNeeded")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with no fields
func (_m *RestartableProcess) Stop() {
	_m.Called()
}

// NewRestartableProcess creates a new instance of RestartableProcess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRestartableProcess(t interface {
	mock.TestingT
	Cleanup(func())
}) *RestartableProcess {
	mock := &RestartableProcess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
